name: corsac_mysql
version: 0.1.0-dev
description: MySQL repositories and utilities based on corsac_dal
homepage: https://github.com/corsac-dart/mysql
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  humps:
    git: https://github.com/pulyaevskiy/dart-humps.git
  corsac_kernel:
    git: https://github.com/corsac-dart/kernel.git
  corsac_state:
    git: https://github.com/corsac-dart/state.git
  corsac_console:
    git: https://github.com/corsac-dart/console.git
  corsac_dal:
    git: https://github.com/corsac-dart/dal.git
  sqljocky:
    git: https://github.com/pulyaevskiy/sqljocky.git

dev_dependencies:
  test: "^0.12.6+1"
